# Site settings
name: 学渣不学渣
email: 1754530626@qq.com
author: qujialin
url: http://www.qujialin.cn
resume_site: https://github.com/qujialin.io
github: https://github.com/qujialin/
baseurl: ""
description: Actually, less is more!
meta_description: 屈佳林;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qujialin

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

