# Site settings
name: 学渣不学渣
email: 1754530626@foxmail.com
author: qujialin
url: http://www.qujialin.cn
resume_site: http://www.qujialin.cn/index.html/
github: https://github.com/qujialin/
baseurl: ""
description: 不安于现状，不甘于平庸！
meta_description: 屈佳林;个人博客;学而不思则罔;思而不学则殆
motto: 学而时习之，不亦说乎?
banner: 学而时习之，不亦说乎?

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qujialin

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

